// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgUpdateMaturityParams } from "./types/prismcore/assets/tx";
import { MsgRegisterAsset } from "./types/prismcore/assets/tx";
import { MsgDisableAsset } from "./types/prismcore/assets/tx";
import { MsgUpdateFeeRatios } from "./types/prismcore/assets/tx";


export { MsgUpdateMaturityParams, MsgRegisterAsset, MsgDisableAsset, MsgUpdateFeeRatios };

type sendMsgUpdateMaturityParamsParams = {
  value: MsgUpdateMaturityParams,
  fee?: StdFee,
  memo?: string
};

type sendMsgRegisterAssetParams = {
  value: MsgRegisterAsset,
  fee?: StdFee,
  memo?: string
};

type sendMsgDisableAssetParams = {
  value: MsgDisableAsset,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateFeeRatiosParams = {
  value: MsgUpdateFeeRatios,
  fee?: StdFee,
  memo?: string
};


type msgUpdateMaturityParamsParams = {
  value: MsgUpdateMaturityParams,
};

type msgRegisterAssetParams = {
  value: MsgRegisterAsset,
};

type msgDisableAssetParams = {
  value: MsgDisableAsset,
};

type msgUpdateFeeRatiosParams = {
  value: MsgUpdateFeeRatios,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgUpdateMaturityParams({ value, fee, memo }: sendMsgUpdateMaturityParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateMaturityParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdateMaturityParams({ value: MsgUpdateMaturityParams.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateMaturityParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRegisterAsset({ value, fee, memo }: sendMsgRegisterAssetParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRegisterAsset: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRegisterAsset({ value: MsgRegisterAsset.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRegisterAsset: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDisableAsset({ value, fee, memo }: sendMsgDisableAssetParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDisableAsset: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDisableAsset({ value: MsgDisableAsset.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDisableAsset: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateFeeRatios({ value, fee, memo }: sendMsgUpdateFeeRatiosParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateFeeRatios: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdateFeeRatios({ value: MsgUpdateFeeRatios.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateFeeRatios: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgUpdateMaturityParams({ value }: msgUpdateMaturityParamsParams): EncodeObject {
			try {
				return { typeUrl: "/prismfinance.prismcore.assets.MsgUpdateMaturityParams", value: MsgUpdateMaturityParams.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateMaturityParams: Could not create message: ' + e.message)
			}
		},
		
		msgRegisterAsset({ value }: msgRegisterAssetParams): EncodeObject {
			try {
				return { typeUrl: "/prismfinance.prismcore.assets.MsgRegisterAsset", value: MsgRegisterAsset.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRegisterAsset: Could not create message: ' + e.message)
			}
		},
		
		msgDisableAsset({ value }: msgDisableAssetParams): EncodeObject {
			try {
				return { typeUrl: "/prismfinance.prismcore.assets.MsgDisableAsset", value: MsgDisableAsset.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDisableAsset: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateFeeRatios({ value }: msgUpdateFeeRatiosParams): EncodeObject {
			try {
				return { typeUrl: "/prismfinance.prismcore.assets.MsgUpdateFeeRatios", value: MsgUpdateFeeRatios.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateFeeRatios: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			PrismfinancePrismcoreAssets: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;